In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [6]:
digits = f"F:\project file\Data Science complet coures\2"

In [7]:
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.2)

AttributeError: 'str' object has no attribute 'data'

In [5]:
print(X_train)

[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  1.  8. ...  0.  0.  0.]
 [ 0.  0.  6. ...  4.  0.  0.]
 ...
 [ 0.  0. 13. ...  0.  0.  0.]
 [ 0.  0.  6. ...  4.  0.  0.]
 [ 0.  0.  1. ...  9.  0.  0.]]


### Logistic Regression

In [4]:
lr = LogisticRegression(solver="liblinear",multi_class='ovr')
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9527777777777777

### SVM

In [5]:
svm = SVC(gamma="auto")
svm.fit(X_train,y_train)
svm.score(X_test, y_test)

0.4222222222222222

### Ramdom Forest

In [6]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9722222222222222

### KFOLD Cross Validation

Basic example

In [7]:
from sklearn.model_selection import KFold
Kf = KFold(n_splits=3)
Kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index,test_index in Kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


### Use Kfold for our digits example

In [9]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [10]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

c:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9638888888888889

In [11]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))


### Cross_val_score_funcation

In [12]:
from sklearn.model_selection import cross_val_score


#### Logistic regression model performance using cross_val_score

In [13]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target,cv=4)

array([0.93777778, 0.91091314, 0.95768374, 0.90423163])

In [14]:
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=4)

array([0.40888889, 0.40534521, 0.43207127, 0.50556793])

In [15]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=4)

array([0.93777778, 0.91314031, 0.96213808, 0.93541203])

### Parameter tunning using k fold validation

In [16]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target,cv=10)
np.average(scores1)
# scores1

0.8831346989447548

In [17]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data,digits.target,cv=10)
np.average(scores2)

0.9321135940409683

In [18]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data,digits.target,cv=10)
np.average(scores3)

0.9415611421477342

In [19]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9443513345747983

Here we used cross_val_score to fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result.