In [1]:
import numpy as np

In [4]:
a1 = np.array([1,2,3])
a2 = np.array([[1],[2],[3]])
a3 = np.array([[[1],[2],[3]]])
a4 = np.array([1,2,3])
a5 = np.array([1,2,3])
print("dimantion of a1",a2.ndim)
print("dimantion of a2",a3.ndim)
print("itemsize of a2",a2.itemsize)
print("1 to 5 give me 10 value ",np.linspace(1,5,10))
print("itemsize of a1",a1.itemsize)



dimantion of a1 2
dimantion of a2 3
itemsize of a2 4
1 to 5 give me 10 value  [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
itemsize of a1 4


In [5]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.shape)
a.reshape(2,3)

(3, 2)


array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
ar = np.array([[1,2],[3,4],[5,6]],dtype=complex)
print(ar.ndim)
print(ar)

2
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [12]:
zero = np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
once = np.ones((4,3))
once

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
I = range(5)
I[4]

4

In [24]:
i = np.arange(1,5)
i = np.arange(1,5,2)
i

array([1, 3])

In [30]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.sum(axis=1)) # 0 represent the colum & 1 is represent the row

[ 3  7 11]


In [31]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])