In [12]:
import numpy as np

In [13]:
a = np.array([[1,2,3],[4,5,6]])

In [14]:
a.sum(axis=0)

array([5, 7, 9])

In [15]:
b = np.array([[7,8,9],[2,8,0]])

In [16]:
a.dot(b.transpose())

array([[ 50,  18],
       [122,  48]])

In [17]:
len(dir(np))

599

In [18]:
np.cross(a,b)

array([[ -6,  12,  -6],
       [-48,  12,  22]])

In [19]:
a = np.array([[11,1,2,3],[12,4,5,6]])
print(np.sort(a,axis=0,kind="mergesort"))

[[11  1  2  3]
 [12  4  5  6]]


In [20]:
%%time
print(np.sort(a,axis=0,kind="mergesort"))

[[11  1  2  3]
 [12  4  5  6]]
CPU times: total: 0 ns
Wall time: 0 ns


In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a = np.array([1,23,132,2,24,23,42,34,423,342,54,324,34,234,35,34,45,34])
a.shape 
# this is count the all element

(18,)

In [23]:
b = a.reshape(6,3) # means is convert the array is dimantion 

In [24]:
np.argsort(b,axis=0)

array([[0, 0, 1],
       [1, 1, 5],
       [4, 2, 4],
       [5, 5, 0],
       [2, 3, 3],
       [3, 4, 2]], dtype=int64)

In [25]:
np.argsort(a)

array([ 0,  3,  1,  5,  4, 15, 12, 17,  7, 14,  6, 16, 10,  2, 13, 11,  9,
        8], dtype=int64)

In [26]:
np.argmax(a)

8

In [27]:
np.argmin(a)

0

In [28]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [29]:
arr1.shape

(3,)

In [30]:
a = np.arange(0,20,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
a = np.linspace(0,10,20)
a

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [32]:
a = np.random.rand(10)
a

array([0.81106907, 0.7015624 , 0.87951835, 0.74242283, 0.68312384,
       0.76560523, 0.86641757, 0.37869541, 0.92506546, 0.12840766])

In [33]:
print(np.zeros(10))
print('/n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[0. 0. 0.]
 [0. 0. 0.]]


In [34]:
print(np.ones((10,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [35]:
arr = [0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [36]:
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [37]:
indentity_matrix = np.eye(3)
indentity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [39]:
arr = np.random.rand(5,5)
arr

array([[0.01958056, 0.02229002, 0.34747684, 0.83811743, 0.91462895],
       [0.93630857, 0.00569453, 0.04255399, 0.84351013, 0.19334623],
       [0.37450885, 0.57751424, 0.78243291, 0.61150599, 0.85030037],
       [0.29894453, 0.16192583, 0.89499361, 0.16894512, 0.60437892],
       [0.13160692, 0.83438318, 0.18557884, 0.9239714 , 0.41123497]])

In [40]:
np.diag(arr)

array([0.01958056, 0.00569453, 0.78243291, 0.16894512, 0.41123497])

In [41]:
arr.ndim

2

In [42]:
arr.shape

(5, 5)

In [43]:
np.random.randint(-10,10,4)

array([ 2, -6,  4, -5])

In [44]:
arr+10

array([[10.01958056, 10.02229002, 10.34747684, 10.83811743, 10.91462895],
       [10.93630857, 10.00569453, 10.04255399, 10.84351013, 10.19334623],
       [10.37450885, 10.57751424, 10.78243291, 10.61150599, 10.85030037],
       [10.29894453, 10.16192583, 10.89499361, 10.16894512, 10.60437892],
       [10.13160692, 10.83438318, 10.18557884, 10.9239714 , 10.41123497]])

In [45]:
arr

array([[0.01958056, 0.02229002, 0.34747684, 0.83811743, 0.91462895],
       [0.93630857, 0.00569453, 0.04255399, 0.84351013, 0.19334623],
       [0.37450885, 0.57751424, 0.78243291, 0.61150599, 0.85030037],
       [0.29894453, 0.16192583, 0.89499361, 0.16894512, 0.60437892],
       [0.13160692, 0.83438318, 0.18557884, 0.9239714 , 0.41123497]])

In [46]:
np.log(arr)

array([[-3.93321792, -3.80361602, -1.05705727, -0.17659705, -0.08923682],
       [-0.06581018, -5.1682496 , -3.15698157, -0.17018337, -1.64327275],
       [-0.98213984, -0.54902218, -0.2453471 , -0.49183053, -0.16216562],
       [-1.20749723, -1.82061688, -0.1109387 , -1.77818132, -0.50355392],
       [-2.02793566, -0.18106254, -1.68427547, -0.07907416, -0.88859052]])

In [47]:
np.log2(arr)

array([[-5.67443399, -5.48745798, -1.52501129, -0.25477569, -0.12874152],
       [-0.09494402, -7.45620807, -4.55456166, -0.2455227 , -2.37074145],
       [-1.41692827, -0.79207157, -0.35396105, -0.70956147, -0.23395554],
       [-1.74205026, -2.62659494, -0.16005071, -2.56537338, -0.72647475],
       [-2.92569272, -0.26121802, -2.42989587, -0.1140799 , -1.28196514]])

In [48]:
np.log10(arr)

array([[-1.70817484, -1.65188945, -0.45907414, -0.07669513, -0.03875506],
       [-0.028581  , -2.24454228, -1.37105968, -0.0739097 , -0.71366429],
       [-0.42653791, -0.2384373 , -0.10655289, -0.21359929, -0.07042763],
       [-0.52440938, -0.79068386, -0.04818006, -0.77225434, -0.21869069],
       [-0.88072127, -0.07863446, -0.73147154, -0.03434147, -0.38590996]])

In [49]:
np.sin(arr)

array([[0.01957931, 0.02228818, 0.34052653, 0.74338526, 0.79233627],
       [0.80537544, 0.0056945 , 0.04254115, 0.74698141, 0.19214384],
       [0.36581547, 0.545943  , 0.70500692, 0.57410119, 0.75147861],
       [0.29451172, 0.16121914, 0.78020509, 0.16814259, 0.56825113],
       [0.13122734, 0.74088237, 0.18451547, 0.79800129, 0.39974164]])

In [50]:
np.cos(arr)

array([[0.99980831, 0.99975159, 0.94023491, 0.66886348, 0.61008462],
       [0.59276504, 0.99998379, 0.99909472, 0.66484492, 0.98136677],
       [0.9306874 , 0.83782232, 0.70920042, 0.81878436, 0.65975746],
       [0.95564787, 0.98691863, 0.6255238 , 0.98576268, 0.82285519],
       [0.9913523 , 0.6716348 , 0.98282961, 0.60265574, 0.91662785]])

In [51]:
np.tan(arr)

array([[0.01958307, 0.02229372, 0.36217176, 1.11141553, 1.29873176],
       [1.35867568, 0.00569459, 0.0425797 , 1.12354232, 0.19579208],
       [0.39305944, 0.65162146, 0.994087  , 0.70116287, 1.13902253],
       [0.30818017, 0.16335606, 1.24728282, 0.17057106, 0.69058461],
       [0.13237205, 1.10310301, 0.18773902, 1.32414121, 0.43610026]])

In [52]:
np.sum(arr)

11.975732954579446

In [53]:
np.min(arr)

0.005694527807951544

In [54]:
np.min(arr,axis=0)

array([0.01958056, 0.00569453, 0.04255399, 0.16894512, 0.19334623])

In [55]:
np.min(arr,axis=1)

array([0.01958056, 0.00569453, 0.37450885, 0.16192583, 0.13160692])

In [56]:
np.max(arr)

0.936308574488253

In [57]:
np.mean(arr)

0.47902931818317784

In [58]:
np.median(arr)

0.41123497188551406

In [59]:
np.std(arr)

0.3355848999155786

In [60]:
np.var(arr)

0.1126172250513489

In [61]:
arr[1:,2:-1]

array([[0.04255399, 0.84351013],
       [0.78243291, 0.61150599],
       [0.89499361, 0.16894512],
       [0.18557884, 0.9239714 ]])

In [62]:
np.sort(arr)

array([[0.01958056, 0.02229002, 0.34747684, 0.83811743, 0.91462895],
       [0.00569453, 0.04255399, 0.19334623, 0.84351013, 0.93630857],
       [0.37450885, 0.57751424, 0.61150599, 0.78243291, 0.85030037],
       [0.16192583, 0.16894512, 0.29894453, 0.60437892, 0.89499361],
       [0.13160692, 0.18557884, 0.41123497, 0.83438318, 0.9239714 ]])

In [63]:
arr[:3,:]

array([[0.01958056, 0.02229002, 0.34747684, 0.83811743, 0.91462895],
       [0.93630857, 0.00569453, 0.04255399, 0.84351013, 0.19334623],
       [0.37450885, 0.57751424, 0.78243291, 0.61150599, 0.85030037]])

In [64]:
arr[:3,:].transpose()

array([[0.01958056, 0.93630857, 0.37450885],
       [0.02229002, 0.00569453, 0.57751424],
       [0.34747684, 0.04255399, 0.78243291],
       [0.83811743, 0.84351013, 0.61150599],
       [0.91462895, 0.19334623, 0.85030037]])

In [65]:
arr[:3,:].flatten()

array([0.01958056, 0.02229002, 0.34747684, 0.83811743, 0.91462895,
       0.93630857, 0.00569453, 0.04255399, 0.84351013, 0.19334623,
       0.37450885, 0.57751424, 0.78243291, 0.61150599, 0.85030037])

In [66]:
arr = np.array([4,5,6,7,8])
arr

array([4, 5, 6, 7, 8])

In [67]:
arr1 = np.append(arr,8)
arr1

array([4, 5, 6, 7, 8, 8])

In [68]:
arr2 = np.insert(arr , 0, [1,2,3])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
arr3 = np.delete(arr1,[4,5])
arr3

array([4, 5, 6, 7])

In [70]:
arr1 = np.array([[1,2,3,4],[1,2,3,4]])
arr2 = np.array([[5,6,7,8],[5,6,7,8]])
arrr_cat = np.concatenate((arr1,arr2),axis=1)
print(arrr_cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [71]:
catV = np.vstack((arr1,arr2))
catV

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [72]:
catH = np.hstack((arr1,arr2))
catH

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [73]:
arr = np.unique([1,2,3,4,5,6,1,2,4])
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [74]:
unique , count = np.unique(arr,return_counts=True)
print(unique)
print(count)

[1 2 3 4 5 6]
[1 1 1 1 1 1]


## intersection,Differention,neither

In [75]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
print(np.intersect1d(arr1,arr2))
print(np.union1d(arr1,arr2))
print(np.setdiff1d(arr1,arr2))
print(np.setxor1d(arr1,arr2))

[3 4 5]
[1 2 3 4 5 6 7]
[1 2]
[1 2 6 7]


In [76]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
print(np.intersect1d(arr1,arr2))

[3 4 5]


### Number for which square root will be caiculated

In [77]:
np_sqrt = np.sqrt([2,4,9,16])


#### Square root value

In [78]:
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

#### Tirgonomaetric funcation

In [79]:
from numpy import pi
np.cos(0)

1.0

In [80]:
np.sin(pi/2)

1.0

In [81]:
np.cos(pi)

-1.0

#### Return the floor of the input element wise

In [82]:
np.floor([1,5,1.6,2.7,3.3,1.1,-0.3,-1.4])

array([ 1.,  5.,  1.,  2.,  3.,  1., -1., -2.])

In [83]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

## Shape Manipulation-Example

#### you can use certain funcation to manipulation the shape of an array to do the following

##### Flattens the dataset

In [84]:
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [85]:
new_cyclist_trials.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

##### Change or reshape the dataset to 3 row and 4 colums

In [86]:
new_cyclist_trials.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

##### Resize agine to 32 row and 6 column

In [87]:
new_cyclist_trials.resize(2,6)

In [88]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

###### Split the array into two

In [89]:
np.hsplit(new_cyclist_trials,2)

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [90]:
new_cyclist_trials.shape

(2, 6)

In [91]:
new_cyclist_trials_1 = np.array([10,15,17,26,13,19])

In [92]:
new_cyclist_trials_2 = np.array([12,11,21,24,14,23])

#### Stack the array togather

In [93]:
np.hstack((new_cyclist_trials_1,new_cyclist_trials_2))

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

## Import numpy Library

In [94]:
import numpy as np

#### First numpy array

In [95]:
first_numpy_array = np.array([1,2,3,4])

#### print first array

In [96]:
print(first_numpy_array)

[1 2 3 4]


#### array with zeros

In [97]:
array_with_zeros = np.zeros((3,2))
array_with_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

##### array with ones

In [98]:
array_with_ones = np.ones((2,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

#### array with arange method

In [99]:
np_arange = np.arange(12)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### linspace for linearly (equal) space data elements

In [100]:
np_linspace = np.linspace(1,6,5)
np_linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

#### one dimensional array

In [101]:
oneD_array = np.arange(15)
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

##### Two dimensional array

In [104]:
Two_dimansional = oneD_array.reshape((3,5))
Two_dimansional

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### Three dimational array

In [116]:
TreeD_array = np.arange(27).reshape(3,3,3)
TreeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])