In [33]:
import numpy as np

In [41]:
def calculate(list):

    if len(list) != 9:
        raise ValueError("input  list must the 9 value")
    
    matrix = np.array(list).reshape((3,3))
    print(matrix)
    # matrix = [
        # [1,4,7],
        # [2,5,8],
        # [3,6,9],
    # ]
    
    mean_row = np.mean(matrix,axis=1)
    mean_column = np.mean(matrix,axis=0)
    mean = np.mean(matrix)
    
    variance_row = np.var(matrix,axis=1)
    variance_columns = np.var(matrix , axis=0)
    variance = np.var(matrix)
    
    standard_deviation_row = np.std(matrix,axis=1)
    standard_deviation_columns = np.std(matrix,axis=0)
    standard_deviation = np.std(matrix)
    
    max_row = np.max(matrix,axis=1)
    max_column = np.max(matrix,axis=0)
    max = np.max(matrix)
    
    min_row = np.min(matrix,axis=1)
    min_columns = np.min(matrix,axis=0)
    main = np.min(matrix)
    
    sum_row = np.sum(matrix,axis=1)
    sum_columns = np.sum(matrix,axis=0)
    sum = np.sum(matrix)
    
    dic_info = {
        'mean_' :[mean_row,mean_column,mean],
        'variance_' : [variance_row,variance_columns,variance], 
        'standard_deviation_': [standard_deviation_row,standard_deviation_columns,standard_deviation],
        'max_':[max_row,max_column,max],
        'min_':[min_row,min_columns,main],
        'sum_':[sum_row,sum_columns,sum]
    }
    for i in dic_info:
        print(dic_info[i])
    
list = [1,2,3,4,5,6,7,8,9]
calculate(list)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([2., 5., 8.]), array([4., 5., 6.]), 5.0]
[array([0.66666667, 0.66666667, 0.66666667]), array([6., 6., 6.]), 6.666666666666667]
[array([0.81649658, 0.81649658, 0.81649658]), array([2.44948974, 2.44948974, 2.44948974]), 2.581988897471611]
[array([3, 6, 9]), array([7, 8, 9]), 9]
[array([1, 4, 7]), array([1, 2, 3]), 1]
[array([ 6, 15, 24]), array([12, 15, 18]), 45]
